<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="423970" started-at="2019-05-01T08:46:02Z" finished-at="2019-05-01T08:53:06Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="423970" started-at="2019-05-01T08:46:02Z" finished-at="2019-05-01T08:53:06Z">
      <class name="testscripts.TC001_MMTFlightBookTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:testscripts.TC001_MMTFlightBookTest@4c203ea1]" name="setUp" is-config="true" duration-ms="32893" started-at="2019-05-01T14:16:02Z" finished-at="2019-05-01T14:16:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="MMTflightSearchTest()[pri:0, instance:testscripts.TC001_MMTFlightBookTest@4c203ea1]" name="MMTflightSearchTest" duration-ms="388808" started-at="2019-05-01T14:16:35Z" finished-at="2019-05-01T14:23:04Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [20734] but found [20842]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [20734] but found [20842]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at testscripts.TC001_MMTFlightBookTest.MMTflightSearchTest(TC001_MMTFlightBookTest.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- MMTflightSearchTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testscripts.TC001_MMTFlightBookTest@4c203ea1]" name="tearDown" is-config="true" duration-ms="2258" started-at="2019-05-01T14:23:04Z" finished-at="2019-05-01T14:23:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testscripts.TC001_MMTFlightBookTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
